#include "AccelerometerDevice.cpp"
#include "CompassDevice.cpp"
#include "DeviceItem.cpp"
#include "GeolocationDevice.cpp"
#include "GyroscopeDevice.cpp"
#include "InputDevice.cpp"
#include "JoystickDevice.cpp"
#include "KeyToAscii.cpp"
#include "KeyboardDevice.cpp"
#include "ModuleInput.cpp"
#include "MouseDevice.cpp"
#include "MultiTouchDevice.cpp"
#include "SpatialInteractionDevice.cpp"
#include "TouchInputEventManager.cpp"
#include "VirtualDevice.cpp"
#include "VirtualSensors.cpp"

