#include "ABaseChannel.cpp"
#include "ABaseStream.cpp"
#include "ABaseSystem.cpp"
#include "AGroupIndexList.cpp"
#include "AObject.cpp"
#include "AObjectResource.cpp"
#include "GenericAnimationModule.cpp"

#include "Bones/ABoneChannel.cpp"
#include "Bones/ABoneSystem.cpp"
#include "Bones/AControledRotationStream.cpp"
#include "Bones/AObjectSkeletonResource.cpp"
#include "Bones/APRSBezierKeyStream.cpp"
#include "Bones/APRSControlStream.cpp"
#include "Bones/APRSKeyStream.cpp"
#include "Bones/APRSStream.cpp"
